import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home = ({ files }: { files: string[] }) => {
  console.log(files);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Submit ur mp4 video</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          List of ur movies
        </h1>
        <div>
          <h2>
          <Link href="/upload/UploadVideo">
            <a style={{color:'blue'}}>Upload More Videos</a>
            </Link>
          </h2>
          {files && files.map((file) => {
            return (
              <div  key={file} style={{display:'grid',placeContent:'center'}}>
              <Link href={`/videos/${file}`}>
                <a style={{color:'blue'}}>Go To {file}</a>
                </Link>
                </div>
            )
          })}
        </div>
      </main>
    </div>
  )
}

Home.getInitialProps = async () => {
  const res = await fetch('http://localhost:3000/api/videosList')
  const json = await res.json()
  return { files: json.files}
}

export default Home
